### ISSUE TITLE
Cost estimates

### ISSUE THREAD

**Issue by johav** [opencultureagency/ASKotec#3]
- Case and Work Surface 
- Adapters and Extra
- Electronic Tools 
- Mechanical Tools 
- Guides and Documentation 
- Other
- Arduino kit? (costs about 60 EUR, we can send one for a donation of 250 or 300 EUR?)
- Soldering tools?
- Basic tools kit?
-  packets assembled with all the bits for a solar light + OHG (donation of 50 EUR)
-  packets assembled with all the bits for a solar charger + OHG (donation of 120 EUR)

**Comment by TWille** [comment]
So you want a price per category?

**Comment by TWille** [comment]
I added a first calculation for Materials, Tools and Total to the [](README.md) and more can be looked up in the new 2.0 Dev Section
