### ISSUE TITLE
Stockroom order login with GitHub as primarily 

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKotec#47]
![grafik](https://user-images.githubusercontent.com/8081055/104135150-7fd41900-538e-11eb-8eb2-f4f0bbb94d46.png)

- [x] GitHub as only Login
- [x] removing the contact form and note to a separate contact form
- [x] changing the GitHub Icon to `GitHub-Logo + GitHub-Text`

**Comment by bmen** [comment]
The Github Icon i could not change it quickly, but i wrote the word github under the icon.
