### ISSUE TITLE
Last ToDos cameroon project

### ISSUE THREAD

**Issue by bmen** [opencultureagency/ASKotec#72]
- [x] 2x #73 with new 2.1 Version
- [x] 2x Sew Velcro to laptop bag
- [x] Order 2x Ointment Gel and 2x desinfection spray
- [x] Order 1x iFixit mobile repair kit
- [x] #74
- [x] ~~2x LED Tester~~

Final Steps to make the 2 Kits ready for field action:
- [ ] #80
- [x] a Packing Guide ready for print (A4)
- [x] one Page print for each ASKmod Packing and laminate (A4)
- [x] add the new printed Open Hardware Guide 2x
- [x] OS on computers including install of other software (ASKotec-Software Repo?) and modifications to firefox etc.
- [x] Final Pictures/Documentation Check → Full BOM Check/Test together with Ngala

**Comment by timmwille** [comment]
I've also added the two chopstick sets

**Comment by timmwille** [comment]
@Ngala

**Comment by timmwille** [comment]
I will close this, all done but the BOM Task is still a ToDo #80
