### ISSUE TITLE
ASKmod repository concept to adopt - create Template Repo?

### ISSUE THREAD

**Issue by timmwille** [opencultureagency/ASKotec#77]
Should have at least: Readme.md, License.md, images folder and a Content.md with: 
- [x] Title
- [x] Overview Picture
- [x] Reference Product Link
- [x] Added Items
- [ ] (optional) Full ASKmod BOM → future versions
- [ ] (otional) removed Items → but this should be more explained in a How To Build Guide, future versions

I think the Content.md can later be also a reference/embedded into the stockroom

**Comment by bmen** [comment]
- README.md: explain "the about" and to give an overview
   - Summary (Dimensions, Weight, technical specs)
   - Explain the repository
   - Explain "the about" reference to ASKotec
   - How to build
- CONTENT.md (see description of the ticket) -> embed in the stockroom + Link to the repo
